### ISSUE TITLE
[Feature Request] Blacklist upgrade

### ISSUE THREAD

**Issue by Robijnvogel** [TheCBProject/Translocators#28]
Quoting [Armigus](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956?comment=24340) :
"An upgrade to make the filter a blacklist instead of a whitelist. Material of your choice... I would go with iron ingot."

**Comment by covers1624** [comment]
IronIngot is already used for redstone output. Never the less ill poke @Chicken-Bones about this. I personally think this would be nice, but I'm unsure what we should use as the item.

**Comment by Robijnvogel** [comment]
I guess Translocator for MC 1.11.2 doesn't work yet?
`java.lang.NoSuchMethodError: codechicken.lib.inventory.InventoryRange.<init>(Lnet/minecraft/inventory/IInventory;I)V
	at codechicken.translocator.tile.TileItemTranslocator.func_73660_a(TileItemTranslocator.java:279)`

Anyways, what upgrades are there?
1. There's Diamond Nuggets for keeping exact quantities.
2. There's Redstone dust to turn the translocator on/off using a redstone signal.
3. There's Iron Ingots that put out a redstone signal when the Translocator it is attached to is pulling/being pulled from? This does not work in Minecraft 1.10.2. I have tried every side of the Translocator **and** the chest and no luck.
4. Glowstone is used to move whole stacks at once.

5. I think a gold nugget or gold ingot would be a good idea to turn the Whitelist into a Blacklist.
An Emerald, Stick, Blaze Rod or Nether Quartz could do as well.
6. Also, while we are busy anyway. Maybe an upgrade to invert the redstone output and one to invert the redstone input would be useful as well for people who like to make compact designs.

EDIT:
Other materials that may be used as an upgrade: Nether Bricks, String ~~and (ultimately) Nether Star~~.
vv Edited No. 4. after cover's following reply vv

**Comment by covers1624** [comment]
Jenkins built something from a branch it wasn't meant to, that was the crash. Anyway, most of these things have been fixed since and pending a release, Glowstone is used for stacks at once.

**Comment by Robijnvogel** [comment]
Are those stable builds going to be uploaded to CurseForge as well?

**Comment by covers1624** [comment]
When things are stable yes, Right now im looking at rewrokig a few systems before i get too deep in to 1.11 and cant do breaking changes easily. Once these changes happen and things are stable new builds will be pushed.

**Comment by Robijnvogel** [comment]
Are you going to do anything for Minecraft 1.10.2, however?
If not, could you make sure that an issue gets created at the main issue tracker, stating your current plans regarding maintenance, updating, etc.?

**Comment by Lost-Ninja** [comment]
I'd suggest Coal/Charcoal to switch to blacklist, and gold/gold nugget to expand the size of the filter.

**Comment by Robijnvogel** [comment]
Sounds reasonable to me. I mean, coal is black and gold is rare/limited (irl) after all.

**Comment by MacAttack-UK** [comment]
I've been using translocators lots recently and the one thing I'm really really missing is a blacklist option.

FTB Revelations 3.2.0 Minecraft 1.12.2

Also as Lost-Ninja suggested coal/charcoal to switch to blacklist and a larger and much larger filter would just be awesome also.

May I give this a bump please :)
